from flask import Flask, send_file, jsonify
from flask_cors import CORS
import os
import glob
from datetime import datetime

app = Flask(__name__)
CORS(app)  # Enable CORS for React frontend

@app.route('/api/export', methods=['GET'])
def export_excel():
    """
    Endpoint to serve the most recent Excel file generated by the detection system.
    Opens in a new tab in the browser.
    """
    try:
        # Find the most recent Excel file in the current directory
        excel_files = glob.glob('vehicle_detections_*.xlsx')
        
        if not excel_files:
            return jsonify({'error': 'No Excel file found. Please run the detection system first.'}), 404
        
        # Get the most recent file
        latest_file = max(excel_files, key=os.path.getctime)
        
        # Send the file
        return send_file(
            latest_file,
            mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            as_attachment=False,  # Open in browser instead of download
            download_name=os.path.basename(latest_file)
        )
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/export/download', methods=['GET'])
def download_excel():
    """
    Endpoint to download the most recent Excel file.
    """
    try:
        # Find the most recent Excel file
        excel_files = glob.glob('vehicle_detections_*.xlsx')
        
        if not excel_files:
            return jsonify({'error': 'No Excel file found. Please run the detection system first.'}), 404
        
        latest_file = max(excel_files, key=os.path.getctime)
        
        # Send the file as download
        return send_file(
            latest_file,
            mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            as_attachment=True,
            download_name=os.path.basename(latest_file)
        )
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/stats', methods=['GET'])
def get_stats():
    """
    Placeholder endpoint for real-time statistics.
    TODO: Integrate with actual detection system.
    """
    return jsonify({
        'totalDetections': 147,
        'highPriority': 12,
        'mediumPriority': 45,
        'lowPriority': 90,
        'withPlates': 98,
        'withoutPlates': 49
    })

@app.route('/api/detections', methods=['GET'])
def get_detections():
    """
    Placeholder endpoint for recent detections.
    TODO: Integrate with actual detection system.
    """
    return jsonify([
        {
            'id': 1,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'vehicle': 'car',
            'priority': 'LOW',
            'plate': 'ABC1234',
            'confidence': 0.85
        }
    ])

@app.route('/api/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({'status': 'ok', 'message': 'API is running'})

if __name__ == '__main__':
    print("Starting Flask API server...")
    print("API will be available at: http://localhost:5000")
    print("\nEndpoints:")
    print("  - GET /api/export          - Open Excel file in browser")
    print("  - GET /api/export/download - Download Excel file")
    print("  - GET /api/stats           - Get detection statistics")
    print("  - GET /api/detections      - Get recent detections")
    print("  - GET /api/health          - Health check")
    
    app.run(debug=True, port=5000, host='0.0.0.0')
